[features]
seeds = false
skip-lint = false

[programs.localnet]
royalpot = "BGvzwkQy2xVLewPANR8siksZJbQD8RN4wKPQczbMRMd5"

[programs.devnet]
royalpot = "BGvzwkQy2xVLewPANR8siksZJbQD8RN4wKPQczbMRMd5"

[programs.mainnet]
royalpot = "BGvzwkQy2xVLewPANR8siksZJbQD8RN4wKPQczbMRMd5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "anchor deploy"
deploy-devnet = "ts-node scripts/deploy-devnet.ts"
initialize = "ts-node scripts/initialize.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
